# Generated by Django 3.2.7 on 2022-02-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('ENTRE', 'Entre'), ('DESSERT', 'Dessert'), ('SOUP', 'Soup'), ('DRINK', 'Drink')], max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Base'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='B', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='delivery.meal')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='delivery.size')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='size',
            field=models.ManyToManyField(related_name='meals', through='delivery.Price', to='delivery.Size'),
        ),
    ]
