# Generated by Django 3.2.7 on 2022-03-06 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_meal_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='delivery.meal')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='delivery.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('delivery', models.BooleanField(default='True')),
                ('delivery_time', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utensils', models.BooleanField(default='False')),
                ('note', models.TextField()),
                ('orderitems', models.ManyToManyField(related_name='carts', to='delivery.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
