# Generated by Django 3.2.7 on 2022-03-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_cart_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
