# Generated by Django 3.2.7 on 2022-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20220320_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderitems',
            field=models.ManyToManyField(blank=True, related_name='carts', to='delivery.OrderItem'),
        ),
    ]
