# Generated by Django 3.2.7 on 2022-03-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_cart_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
